/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlogPost: typeof import('./../components/BlogPost.vue')['default']
    BlogPostDetail: typeof import('./../components/BlogPostDetail.vue')['default']
    BlurReveal: typeof import('./../components/ui/blur-reveal/BlurReveal.vue')['default']
    Demo: typeof import('./../components/Demo.vue')['default']
    GetLivingState: typeof import('./../components/GetLivingState.vue')['default']
    InsertBlogPost: typeof import('./../components/InsertBlogPost.vue')['default']
    InsertLivingState: typeof import('./../components/InsertLivingState.vue')['default']
    LampEffect: typeof import('./../components/ui/lamp-effect/LampEffect.vue')['default']
    Login: typeof import('./../components/Login.vue')['default']
    ParticleWhirlpoolBg: typeof import('./../components/ui/bg-particle-whirlpool/ParticleWhirlpoolBg.vue')['default']
    ResultPage: typeof import('./../components/ResultPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Splash: typeof import('./../components/Splash.vue')['default']
  }
}
